spring.application.name=order
server.port=8081
spring.datasource.url=jdbc:h2:file:./data/orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=me
spring.datasource.password=3737
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console